"""Telemetry schema: salinity/temp/ph -> Float; add pollutants; drop pollution_level & dissolved_oxygen; rename pH->ph

Revision ID: 595d5bb04b66
Revises: 
Create Date: 2025-09-07 15:29:08.743434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595d5bb04b66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ph', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pollutants', sa.Text(), nullable=True))
        batch_op.alter_column('salinity',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_telemetry_buoy_id'), ['buoy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('pollution_level')
        batch_op.drop_column('dissolved_oxygen')
        batch_op.drop_column('pH')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pH', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('dissolved_oxygen', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('pollution_level', sa.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_telemetry_timestamp'))
        batch_op.drop_index(batch_op.f('ix_telemetry_buoy_id'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('salinity',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('pollutants')
        batch_op.drop_column('ph')

    # ### end Alembic commands ###
